package com.music.yzmusic.playback.smart

import kotlin.math.max
import kotlin.math.min
import kotlin.math.roundToLong

/**
 * Canonical Automix 2.0 Transition Duration Policy.
 *
 * Defines hard contracts, musical preferred ranges, and safety invariants for all
 * transitions generated by Automix.
 *
 * Target:
 * - Preferred: 10–15 seconds
 * - Extended: 15–20 seconds
 * - Absolute Maximum: 30 seconds
 * - Invariant: 0s < transitionDuration <= 30s
 * - No transition may ever exceed 30 seconds.
 */
object AutomixDurationPolicy {
    /** Target preferred duration floor for standard musical transitions. */
    const val PREFERRED_MIN_SECONDS = 10.0

    /** Target preferred duration ceiling for standard musical transitions. */
    const val PREFERRED_MAX_SECONDS = 15.0

    /** Extended transition floor when musical structure genuinely benefits from it. */
    const val EXTENDED_MIN_SECONDS = 15.0

    /** Extended transition ceiling; durations above this are heavily penalized. */
    const val EXTENDED_MAX_SECONDS = 20.0

    /** Absolute hard ceiling across the entire Automix pipeline. NEVER exceed this. */
    const val ABSOLUTE_MAX_SECONDS = 30.0
    const val ABSOLUTE_MAX_MS = 30_000L

    /** Safe lower bound to avoid abrupt clicks on very fast handoffs. */
    const val SAFE_MIN_SECONDS = 3.0
    const val SAFE_MIN_MS = 3_000L

    /** Target preferred duration floor for standard musical transitions. */
    const val PREFERRED_MIN_MS = 10_000L

    /** Target preferred duration ceiling for standard musical transitions. */
    const val PREFERRED_MAX_MS = 15_000L

    /** Extended transition floor and ceiling. */
    const val EXTENDED_MIN_MS = 15_000L
    const val EXTENDED_MAX_MS = 20_000L

    /** Default fallback duration when analysis is missing, pending, or low-confidence. */
    const val DEFAULT_FALLBACK_SECONDS = 11.0
    const val DEFAULT_FALLBACK_MS = 11_000L

    /** Maximum fraction of track duration a transition may span for short tracks. */
    const val SHORT_TRACK_MAX_FRACTION = 0.40

    /**
     * Clamps proposed transition duration in seconds against the canonical contract
     * and usable track audio limits.
     *
     * Invariant:
     * 0.0 < return <= 30.0
     */
    fun clampDuration(
        durationSeconds: Double,
        trackDuration: Double = 0.0,
        nextTrackDuration: Double = 0.0,
    ): Double {
        if (!durationSeconds.isFinite() && !durationSeconds.isNaN()) {
            return ABSOLUTE_MAX_SECONDS
        }
        if (trackDuration < 0.0 || nextTrackDuration < 0.0) return 0.0

        val baseDuration = when {
            durationSeconds.isNaN() -> DEFAULT_FALLBACK_SECONDS
            durationSeconds < SAFE_MIN_SECONDS -> SAFE_MIN_SECONDS
            durationSeconds > ABSOLUTE_MAX_SECONDS -> ABSOLUTE_MAX_SECONDS
            else -> durationSeconds
        }

        // Bounded by outgoing and incoming track lengths so short tracks never suffer absurd overlaps
        val outgoingLimit = if (trackDuration > 0.0) {
            trackDuration * SHORT_TRACK_MAX_FRACTION
        } else {
            ABSOLUTE_MAX_SECONDS
        }
        val incomingLimit = if (nextTrackDuration > 0.0) {
            nextTrackDuration * SHORT_TRACK_MAX_FRACTION
        } else {
            ABSOLUTE_MAX_SECONDS
        }

        val trackLimit = min(outgoingLimit, incomingLimit)
        val upperLimit = min(ABSOLUTE_MAX_SECONDS, trackLimit)
        val lowerLimit = min(SAFE_MIN_SECONDS, upperLimit)

        return baseDuration.coerceIn(lowerLimit, upperLimit)
    }

    /**
     * Clamps duration in milliseconds for the playback engine / ExoPlayer scheduling.
     */
    fun clampFadeMs(
        fadeMs: Long,
        trackDurationMs: Long = 0L,
        nextTrackDurationMs: Long = 0L,
    ): Long {
        val durationSec = if (fadeMs > 0L) fadeMs / 1000.0 else DEFAULT_FALLBACK_SECONDS
        val trackSec = if (trackDurationMs > 0L) trackDurationMs / 1000.0 else 0.0
        val nextSec = if (nextTrackDurationMs > 0L) nextTrackDurationMs / 1000.0 else 0.0
        return (clampDuration(durationSec, trackSec, nextSec) * 1000.0).roundToLong()
    }
}
